### ISSUE TITLE
Trying to understand.

### ISSUE THREAD

**Issue by gdey** [yofu/dxf#13]
Hello, first of thank you for this wonderful library.

I'm trying to understand the code, to improve it for my needs. 

I noticed that something have a `WriteTo(f format.Formatter)` in order to generate
the formatted text while other have a `Format(f format.Formatter)`. 

Why the two different methods, it's not clear how they are supposed to differ.

Thank you,

Gautam.

Reading through the code, it seems that unifying it into only the `Format(format.Formatter)` makes the most sense.

**Comment by yofu** [comment]
Hello.
Thank you for reading the code and contributing this library.

As for `WriteTo` and `Format`, there are no significant difference between them.
It seems to be introduced when I implemented `Formatter` in 8cedcfc.
It will be nice to rename `Section.WriteTo(format.Formatter)` to `Section.Format(format.Formatter)`.

I will revise code later to use `Section.Format` instead of `Section.WriteTo`.

**Comment by yofu** [comment]
Committed as 5a6d1e8.
